# This file has been auto-generated by tools/generate_ast.py
# Do not edit this file by hand. Or do, but it will be overwritten

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import List, Optional

from yaplox.expr import Expr, Variable
from yaplox.token import Token


class StmtVisitor(ABC):
    """This class is used as an Vistor for the Stmt class"""

    @abstractmethod
    def visit_block_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_class_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_expression_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_function_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_if_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_print_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_return_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_var_stmt(self, stmt ):
        raise NotImplementedError

    @abstractmethod
    def visit_while_stmt(self, stmt ):
        raise NotImplementedError


class Stmt(ABC):
    @abstractmethod
    def accept(self, visitor ):
        raise NotImplementedError


class Block(Stmt):
    def __init__(self, statements ):
        self.statements = statements

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_block_stmt(self)


class Class(Stmt):
    def __init__(
        self, name , superclass , methods 
    ):
        self.name = name
        self.superclass = superclass
        self.methods = methods

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_class_stmt(self)


class Expression(Stmt):
    def __init__(self, expression ):
        self.expression = expression

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_expression_stmt(self)


class Function(Stmt):
    def __init__(self, name , params , body ):
        self.name = name
        self.params = params
        self.body = body

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_function_stmt(self)


class If(Stmt):
    def __init__(self, condition , then_branch , else_branch ):
        self.condition = condition
        self.then_branch = then_branch
        self.else_branch = else_branch

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_if_stmt(self)


class Print(Stmt):
    def __init__(self, expression ):
        self.expression = expression

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_print_stmt(self)


class Return(Stmt):
    def __init__(self, keyword , value ):
        self.keyword = keyword
        self.value = value

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_return_stmt(self)


class Var(Stmt):
    def __init__(self, name , initializer ):
        self.name = name
        self.initializer = initializer

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_var_stmt(self)


class While(Stmt):
    def __init__(self, condition , body ):
        self.condition = condition
        self.body = body

    def accept(self, visitor ):
        """ Create a accept method that calls the visitor. """
        return visitor.visit_while_stmt(self)
